// Lits if header files to be included in this program


#include "./Memory.hh"
#include "./InputArguments.hh"
#include "./Allocate.hh"
#include "./Tools.hh"
#include "./SetParameters.hh"
#include "./WaveVectors.hh"
#include "./OmegaFields.hh"
#include "./Slope_Calc.hh"
#include "./Slope_Calc2.hh"
#include "./SolveModifiedDiffusionEquation.hh"
#include "./AArrays.hh"
#include "./SolvePoissonBoltzmannEquation.hh"
#include "./ConcAB.hh"
#include "./ConcI.hh"
#include "./HomogeneousFreeEnergy.hh"
#include "./Incompressibility.hh"
#include "./WriteReadFiles.hh"
#include "./FreeEnergyOptimizeBox.hh"
#include "./OptimizeBox1D.hh"
#include "./OptimizeBox2D.hh"
#include "./FreeEnergy.hh"
#include "./SaveData.hh"
#include "../MODS/MOD_main.hh"
